name: jenkins-agent-amazonlinux2-nodejs16

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "5 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Packages Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "TODAY=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
      - name: build :${{env.TODAY}} image
        run: |
          docker build -t ghcr.io/amachsoftware/jenkins-agent-amazonlinux2-nodejs16:${{env.TODAY}} .
      - name: publish jenkins-agent-amazonlinux2-nodejs16:${{env.TODAY}} image
        run: |
          docker push ghcr.io/amachsoftware/jenkins-agent-amazonlinux2-nodejs16:${{env.TODAY}}
          docker tag ghcr.io/amachsoftware/jenkins-agent-amazonlinux2-nodejs16:${{env.TODAY}} ghcr.io/amachsoftware/jenkins-agent-amazonlinux2-nodejs16:latest
          docker push ghcr.io/amachsoftware/jenkins-agent-amazonlinux2-nodejs16:latest
